CREATE TABLE IF NOT EXISTS instruments (
    id BIGSERIAL PRIMARY KEY,
    exchange TEXT NOT NULL,
    category TEXT NOT NULL,
    symbol TEXT NOT NULL,
    base_coin TEXT NOT NULL,
    quote_coin TEXT NOT NULL,
    status TEXT NOT NULL,
    tick_size NUMERIC(38, 18) NOT NULL,
    qty_step NUMERIC(38, 18) NOT NULL,
    min_order_qty NUMERIC(38, 18) NOT NULL,
    max_order_qty NUMERIC(38, 18) NOT NULL,
    max_market_order_qty NUMERIC(38, 18) NOT NULL,
    min_notional_value NUMERIC(38, 18) NOT NULL,
    price_scale INTEGER NOT NULL,
    leverage_filter_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    price_filter_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    lot_size_filter_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    raw_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT instruments_identity_unique UNIQUE (exchange, category, symbol),
    CONSTRAINT instruments_positive_tick_size CHECK (tick_size > 0),
    CONSTRAINT instruments_positive_qty_step CHECK (qty_step > 0),
    CONSTRAINT instruments_non_negative_min_notional CHECK (min_notional_value >= 0)
);

CREATE TABLE IF NOT EXISTS candles (
    id BIGSERIAL PRIMARY KEY,
    exchange TEXT NOT NULL,
    category TEXT NOT NULL,
    symbol TEXT NOT NULL,
    interval TEXT NOT NULL,
    open_time TIMESTAMPTZ NOT NULL,
    close_time TIMESTAMPTZ NOT NULL,
    open NUMERIC(38, 18) NOT NULL,
    high NUMERIC(38, 18) NOT NULL,
    low NUMERIC(38, 18) NOT NULL,
    close NUMERIC(38, 18) NOT NULL,
    volume NUMERIC(38, 18) NOT NULL,
    turnover NUMERIC(38, 18) NOT NULL,
    is_closed BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT candles_identity_unique UNIQUE (exchange, category, symbol, interval, open_time),
    CONSTRAINT candles_close_after_open_time CHECK (close_time > open_time),
    CONSTRAINT candles_positive_open CHECK (open > 0),
    CONSTRAINT candles_positive_high CHECK (high > 0),
    CONSTRAINT candles_positive_low CHECK (low > 0),
    CONSTRAINT candles_positive_close CHECK (close > 0),
    CONSTRAINT candles_non_negative_volume CHECK (volume >= 0),
    CONSTRAINT candles_non_negative_turnover CHECK (turnover >= 0),
    CONSTRAINT candles_high_gte_low CHECK (high >= low),
    CONSTRAINT candles_high_gte_open CHECK (high >= open),
    CONSTRAINT candles_high_gte_close CHECK (high >= close),
    CONSTRAINT candles_low_lte_open CHECK (low <= open),
    CONSTRAINT candles_low_lte_close CHECK (low <= close)
);

CREATE INDEX IF NOT EXISTS candles_symbol_interval_time_idx
    ON candles (exchange, category, symbol, interval, open_time);
